"""add transactions

Revision ID: 3126161187b2
Revises: ec48d2ccdf29
Create Date: 2025-11-08 04:47:20.396612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3126161187b2'
down_revision = 'ec48d2ccdf29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=20), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('processor_status', sa.String(length=40), nullable=True),
    sa.Column('payment_intent_id', sa.String(length=64), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('merchant', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_tx_user_cat_ts', ['user_id', 'category', 'ts'], unique=False)
        batch_op.create_index('ix_tx_user_ts', ['user_id', 'ts'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_tx_user_ts')
        batch_op.drop_index('ix_tx_user_cat_ts')

    op.drop_table('transactions')
    # ### end Alembic commands ###
