"""add external_sub

Revision ID: eedd2774571f
Revises: 9e4dcc197e31
Create Date: 2025-11-08 02:19:33.560293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eedd2774571f'
down_revision = '9e4dcc197e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_sub', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_external_sub'), ['external_sub'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_external_sub'))
        batch_op.drop_column('external_sub')

    # ### end Alembic commands ###
